Repository wireui/wireui, pull requests merged in 2022-07, with the labels that each got.

#367 Hotfix/modal
  dist/mix-manifest.json
  dist/wireui.js
  resources/views/components/modal-card.blade.php
  resources/views/components/modal.blade.php
  tests/TypeScript/alpine/store/index.spec.ts
  tests/TypeScript/alpine/store/modal.spec.ts
  tests/TypeScript/helpers.ts
  ts/alpine/store/index.ts
  ts/alpine/store/modal.ts
  ts/components/alpine.ts
  ts/components/modal.ts
  ts/components/modules/focusables.ts
Labels: hotfix

#375 Fix select subcomponents not using unique keys
  resources/views/components/select.blade.php
Labels: Approved

#379 Set 6 different positions of the notification
  resources/views/components/notifications.blade.php
  src/View/Components/Notifications.php
Labels: Review in Progress

#381 feat: toggle select options on focus
  resources/views/components/select.blade.php
Labels: Changes Requested

#376 Added avatars and basic options
  dist/mix-manifest.json
  dist/wireui.css
  resources/views/components/avatar.blade.php
  src/View/Components/Avatar.php
  src/config/wireui.php
  tests/Unit/Components/AvatarTest.php
Labels: approved, feature

#398 feat: extract card preferences in config
  src/View/Components/Card.php
  src/config/wireui.php
Labels: approved, feature

#408 Hotfix/issue-404-get-params
  dist/mix-manifest.json
  dist/wireui.js
  package.json
  ts/components/select/index.ts
  yarn.lock
Labels: hotfix
