Repository wireui/wireui, pull requests merged in 2022-08, with the labels that each got.

#425 Feature/select-lazy-options
  dist/mix-manifest.json
  dist/wireui.css
  dist/wireui.js
  resources/views/components/select.blade.php
  resources/views/components/select/option.blade.php
  src/View/Components/Select.php
  src/View/Components/Select/Option.php
  tests/Unit/Components/SelectTest.php
  ts/components/select/index.ts
  ts/components/select/interfaces.ts
  ts/components/select/templates/baseTemplate.ts
  ts/components/select/types.ts
Labels: enhancement

#434 Feature/issue-433-add-X-Requested-With-header
  dist/mix-manifest.json
  dist/wireui.js
  ts/components/select/index.ts
Labels: enhancement

#439 fix text highlight
  resources/views/components/select.blade.php
Labels: hotfix

#395 Add Password Input Component
  resources/views/components/input.blade.php
  resources/views/components/inputs/password.blade.php
  src/View/Components/Inputs/PasswordInput.php
  src/config/wireui.php
  tests/Browser/CurrencyInput/Component.php
  tests/Browser/CurrencyInput/view.blade.php
  tests/Browser/Input/view.blade.php
  tests/Browser/PasswordInput/Component.php
  tests/Browser/PasswordInput/Test.php
  tests/Browser/PasswordInput/view.blade.php
  ts/components/index.ts
  ts/components/inputs/password.ts
Labels: approved, feature

#414 Add Input Number Component
  .github/workflows/tests.yml
  js/tailwindcss/plugins/appearance-none.js
  package.json
  resources/views/components/color-picker.blade.php
  resources/views/components/inputs/number.blade.php
  src/View/Components/Inputs/NumberInput.php
  src/config/wireui.php
  tailwind.config.js
  tests/Browser/NumberInput/Component.php
  tests/Browser/NumberInput/Test.php
  tests/Browser/NumberInput/view.blade.php
  tests/TypeScript/helpers.ts
  ts/alpine/directives/index.ts
  ts/components/alpine.ts
  ts/components/index.ts
  ts/components/inputs/number.ts
  ts/index.ts
  yarn.lock
Labels: changes requested, feature
